/* OFFERS */
export const GET_OFFERS_ACCEPTED = "GET_OFFERS_ACCEPTED"
export const GET_OFFERS_ACCEPTED_SUCCESS = "GET_OFFERS_ACCEPTED_SUCCESS"
export const GET_OFFERS_ACCEPTED_FAIL = "GET_OFFERS_ACCEPTED_FAIL"

export const GET_OFFERS_REJECTED = "GET_OFFERS_REJECTED"
export const GET_OFFERS_REJECTED_SUCCESS = "GET_OFFERS_REJECTED_SUCCESS"
export const GET_OFFERS_REJECTED_FAIL = "GET_OFFERS_REJECTED_FAIL"

export const POST_OFFERS_FILE_UPLOAD = "POST_OFFERS_FILE_UPLOAD"
export const POST_OFFERS_FILE_UPLOAD_SUCCESS = "POST_OFFERS_FILE_UPLOAD_SUCCESS"
export const POST_OFFERS_FILE_UPLOAD_FAIL = "POST_OFFERS_FILE_UPLOAD_FAIL"

/* OFFERS DETAIL*/
export const GET_OFFER_BY_PURCHASE = "GET_OFFER_BY_PURCHASE"
export const GET_OFFER_BY_PURCHASE_SUCCESS = "GET_OFFER_BY_PURCHASE_SUCCESS"
export const GET_OFFER_BY_PURCHASE_FAIL = "GET_OFFER_BY_PURCHASE_FAIL"
