/* PURCHASES */
export const GET_PURCHASES = "GET_PURCHASES"
export const GET_PURCHASES_SUCCESS = "GET_PURCHASES_SUCCESS"
export const GET_PURCHASES_FAIL = "GET_PURCHASES_FAIL"

/* PURCHASES DETAIL*/
export const GET_PURCHASE_DETAIL = "GET_PURCHASE_DETAIL"
export const GET_PURCHASE_DETAIL_SUCCESS = "GET_PURCHASE_DETAIL_SUCCESS"
export const GET_PURCHASE_DETAIL_FAIL = "GET_PURCHASE_DETAIL_FAIL"
